name: Publish a Ruby gem
description: Build and publish a Ruby gem
author: Umbrellio
branding:
  icon: upload-cloud
  color: red
inputs:
  api-key:
    description: Rubygems.org API key
    required: true
  working-directory:
    description: Working directory
    required: false
    default: .
runs:
  using: composite
  steps:
    - run: ruby $GITHUB_ACTION_PATH/main.rb
      shell: bash
      env:
        GEM_HOST_API_KEY: ${{inputs.api-key}}
        WORKDIR: ${{inputs.working-directory}}
